# Generated by Django 3.0.6 on 2020-05-28 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255, verbose_name='Rua')),
                ('complement', models.CharField(max_length=255, verbose_name='Complemento')),
                ('neighborhood', models.CharField(max_length=255, verbose_name='Bairro')),
                ('locality', models.CharField(max_length=255, verbose_name='Localidade')),
                ('uf', models.CharField(max_length=255, verbose_name='UF')),
                ('number', models.CharField(max_length=10, verbose_name='Número')),
                ('zip_code', models.CharField(max_length=20, verbose_name='CEP')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do produto')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('cnpj', models.CharField(max_length=255, verbose_name='CNPJ')),
                ('password', models.CharField(max_length=50, verbose_name='Senha')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='register.Address', verbose_name='Endereço')),
            ],
        ),
    ]
