# Generated by Django 3.0.6 on 2020-05-28 21:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField(verbose_name='Altura do pacote (cm)')),
                ('width', models.FloatField(verbose_name='Largura do pacote (cm)')),
                ('length', models.FloatField(verbose_name='Comprimento do pacote (cm)')),
                ('dimensions', models.FloatField(verbose_name='Dimensões (cm)')),
                ('weight', models.FloatField(verbose_name='Peso do pacote (kg)')),
                ('quantity_of_packages', models.IntegerField(verbose_name='Quantidade de pacotes')),
                ('value', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Valor total do pacote')),
                ('products', models.ManyToManyField(to='register.Product', verbose_name='Produtos')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2020, 5, 28, 18, 20, 34, 98950), verbose_name='Data e hora da criação')),
                ('order_pickup_date', models.DateTimeField(verbose_name='Data e hora da retirada')),
                ('delivery_date', models.DateTimeField(verbose_name='Data e hora da entrega')),
                ('destiny', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_destiny', to='register.Address', verbose_name='Destino')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_origin', to='register.Address', verbose_name='Origem')),
                ('packages', models.ManyToManyField(to='order.Package', verbose_name='Pacotes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='register.User', verbose_name='Cliente')),
            ],
        ),
    ]
